baseURL = "https://47.105.106.73/"
languageCode = "zh-CN"
relativeURLs = true
title = "LoRa Server, 开源 LoRaWAN 网络服务器"
googleAnalytics = "UA-3512995-9"
pygmentsUseClasses = true

[[menu.main]]
    pre = "<i class='fas fa-hand-point-right'></i>"
    name = "总览"
    identifier = "overview"
    url = "/overview/"
    weight = 1

[[menu.main]]
    pre = "<i class='fas fa-book-open'></i>"
    name = "指南"
    identifier = "guides"
    url = "/guides/"
    weight = 2

[[menu.main]]
    pre = "<i class='fas fa-download'></i>"
    name = "安装"
    identifier = "install"
    url = "/install/"
    weight = 3

[[menu.main]]
    pre = "<i class='fab fa-github'></i>"
    name = "社区 & 支持"
    identifier = "community"
    url = "/community/"
    weight = 4
